### ISSUE TITLE
Weekly time card bug

### ISSUE THREAD

**Issue by bridget-tan** [ABTech/tracker#404] opened 2019-11-10 00:08 UTC
![Screenshot_2019-11-09-19-02-38](https://user-images.githubusercontent.com/15388532/68536649-1688ee00-0324-11ea-9974-adc0bed1d038.png)
Bug with creating weekly time cards where the time cards are shifting back a day each week (for the last few weeks) instead of consistently starting and ending on mondays

**Comment by timparenti** [comment] 2019-11-10 03:19
Given the dates in question, this might be something cascading related to DST having ended, since naïvely adding a week could land an hour shy of the logical time that is a week later.

**Comment by timparenti** [comment] 2020-02-12 04:35
It turns out it's a combination of naïve date arithmetic, the fact that timecards start on Mondays, and date truncation which results in this manifesting twice consecutively around the fall time change, but not in the spring. 

Adding a week to Monday 10/28 was intended to get Monday 11/4. But the bug actually caused 604800 seconds to be added to Monday 10/28 00:00 EDT, which landed an hour short, at Sunday 11/3 23:00 EST (after the time change). However, since the new timecard form only takes the date portion of this time, Sunday 11/3 00:00 EDT was the result, which is back _before_ the time change. Starting from the erroneous Sunday 11/3 similarly traversed the time change and landed an hour short again, which was truncated to Saturday 11/9.

**Closed** 2020-02-25 00:13 UTC
Labels: Bug, Super Important
